// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYl2zQ02u9rOi28N_K8ACrx6JNF_uwtlc',
    appId: '1:816990293118:web:e8b462650e7f6e4ace5c2f',
    messagingSenderId: '816990293118',
    projectId: 'tintin-money',
    authDomain: 'tintin-money.firebaseapp.com',
    storageBucket: 'tintin-money.firebasestorage.app',
    measurementId: 'G-E5MBN3WK69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmT_ooYk-zPWFOV02RyX2QCOOkRIFksLc',
    appId: '1:816990293118:android:24bb8b71cd4b6438ce5c2f',
    messagingSenderId: '816990293118',
    projectId: 'tintin-money',
    storageBucket: 'tintin-money.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6gq90T6oYc0x_f_as6Y5-gUjZ0GcIhZM',
    appId: '1:816990293118:ios:df71f995fd81ce92ce5c2f',
    messagingSenderId: '816990293118',
    projectId: 'tintin-money',
    storageBucket: 'tintin-money.firebasestorage.app',
    iosBundleId: 'com.example.tintinMoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6gq90T6oYc0x_f_as6Y5-gUjZ0GcIhZM',
    appId: '1:816990293118:ios:df71f995fd81ce92ce5c2f',
    messagingSenderId: '816990293118',
    projectId: 'tintin-money',
    storageBucket: 'tintin-money.firebasestorage.app',
    iosBundleId: 'com.example.tintinMoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYl2zQ02u9rOi28N_K8ACrx6JNF_uwtlc',
    appId: '1:816990293118:web:aeccdadb01b39984ce5c2f',
    messagingSenderId: '816990293118',
    projectId: 'tintin-money',
    authDomain: 'tintin-money.firebaseapp.com',
    storageBucket: 'tintin-money.firebasestorage.app',
    measurementId: 'G-8L1L7YT6YE',
  );
}
